source 'https://rubygems.org'
gem 'rails', '4.2.4'
gem 'authlogic'
gem 'cancancan'
gem 'coffee-rails'
gem 'bower-rails'
gem 'gon'
gem 'jbuilder'
gem 'jquery-rails'
gem 'pg'
gem 'rack-cors'
gem 'sass-rails'
gem 'uglifier'
gem 'websocket-rails'
gem 'vkontakte_api', '~> 1.4'
gem 'angularjs-rails'
gem 'faye-websocket', '0.10.0'

group :development do
  gem 'byebug'
  gem 'debbie'
  gem 'quiet_assets'
  gem 'spring'
end
