default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: musicbox_development
  username: postgres
  password: test
  host: localhost
  # port: 5432
  # schema_search_path: myapp,sharedapp,public
  # min_messages: notice

test:
  <<: *default
  database: musicbox_test

# DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
