# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd583ef136f4884b2cda8cba1637e56f97babd21a4649c9284b6ad19a00c898840615525582a7c8e5ae41ed936db35eb65450b0beae6b2b1d9eacfaf1588e07

test:
  secret_key_base: ca664361846d0682725b72e1c855a6d514e7fd1203806676e26672068f4540136deceea9d664e3ca53603616999c543128218867bbc3d11881b4212e164517a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
